### ISSUE TITLE
Getting error while trying to use the plugin

### ISSUE THREAD

**Issue by pablokbs** [komazarari/capistrano-s3_archive#9]
Hey, I'm trying to use this plugin but I'm getting some errors:

```
cap local deploy --trace
** Invoke local (first_time)
** Execute local
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy (first_time)
** Execute deploy
** Invoke deploy:starting (first_time)
** Execute deploy:starting
** Invoke deploy:check (first_time)
** Execute deploy:check
** Invoke s3_archive:check (first_time)
** Execute s3_archive:check
cap aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/capistrano-s3_archive-0.3.9/lib/capistrano/s3_archive.rb:75:in `check'
/Library/Ruby/Gems/2.0.0/gems/capistrano-s3_archive-0.3.9/lib/capistrano/tasks/s3_archive.rake:10:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => s3_archive:check
The deploy has failed with an error: undefined method `[]' for nil:NilClass
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

I checked that file and it seems like is looking for my ssh keys?

My deploy.rb file:

```
lock '3.4.0'
set :application, 'node-myapp'
set :deploy_to, '/var/www/my_path'
set :scm, :s3_archive
set :repo_url, 's3://my-bucket/my-dir'
set :s3_client_options, { region: 'us-east-1', access_key_id: 'xxxxxxx', secret_access_key: 'yyyyyy' }
set :ssh_options, { keys: %w(/Users/my_user/.ssh/id_rsa) }

namespace :deploy do

  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything such as:
      # within release_path do
      #   execute :rake, 'cache:clear'
      # end
    end
  end

end
```

My local.rb

```
server '127.0.0.1', user: 'vagrant', roles: %w{web}
role :web, %w{node@127.0.0.1:2202}
```

Any ideas?

**Comment by komazarari** [comment]
@pablokbs,
Thank you very much for your reporting.

Global `set :ssh_config` is not working for this plugin, it's a my bug. I will fix this .

or, now you probably can avoid this errors by:
```
server '127.0.0.1', user: 'vagrant', roles: %w{web}, ssh_options: { .... }
```
instead of `set :ssh_option, { ... }`, please try it as workaround if you needed.

**Comment by komazarari** [comment]
I fixed the issue with https://github.com/komazarari/capistrano-s3_archive/pull/10 and released.

**Comment by pablokbs** [comment]
That fixed my issue. Thank you. I'm still having some issues (it's not actually copying files to S3) but I'll keep digging, maybe I'm missing something

**Comment by pablokbs** [comment]
Ok so now is doing just the rsync, I don't see anything on my bucket and I don't see any step or error while trying to use the bucket:

```
$ sudo gem install 'capistrano-s3_archive'
Fetching: capistrano-s3_archive-0.3.10.gem (100%)
Successfully installed capistrano-s3_archive-0.3.10
Parsing documentation for capistrano-s3_archive-0.3.10
Installing ri documentation for capistrano-s3_archive-0.3.10
Done installing documentation for capistrano-s3_archive after 0 seconds
1 gem installed
$ cap local deploy_only
INFO [1990b970] Running /usr/bin/env mkdir -p /var/www/my_app_path/shared /var/www/my_app_path/releases as node@127.0.0.1
DEBUG [1990b970] Command: /usr/bin/env mkdir -p /var/www/my_app_path/shared /var/www/my_app_path/releases
INFO [1990b970] Finished in 0.284 seconds with exit status 0 (successful).
DEBUG [1affe6f1] Running /usr/bin/env [ -f /var/www/my_app_path/current/REVISION ] as node@127.0.0.1
DEBUG [1affe6f1] Command: [ -f /var/www/my_app_path/current/REVISION ]
DEBUG [1affe6f1] Finished in 0.003 seconds with exit status 0 (successful).
DEBUG [9a9bf363] Running /usr/bin/env cat /var/www/my_app_path/current/REVISION 2>/dev/null as node@127.0.0.1
DEBUG [9a9bf363] Command: /usr/bin/env cat /var/www/my_app_path/current/REVISION 2>/dev/null
DEBUG [9a9bf363]        pablo/
DEBUG [9a9bf363] Finished in 0.005 seconds with exit status 0 (successful).
INFO Skip extructing and staging.
DEBUG [04cb0303] Running /usr/bin/env ls -xtr tmp/archives/local as kbs@localhost
DEBUG [04cb0303] Command: /usr/bin/env ls -xtr tmp/archives/local
DEBUG [04cb0303]        pablo
DEBUG [04cb0303] Finished in 0.010 seconds with exit status 0 (successful).
INFO [3a427b8b] Running /usr/bin/env mkdir -p /var/www/my_app_path/releases/20160209164314 as node@127.0.0.1
DEBUG [3a427b8b] Command: /usr/bin/env mkdir -p /var/www/my_app_path/releases/20160209164314
INFO [3a427b8b] Finished in 0.005 seconds with exit status 0 (successful).
INFO [7c3fd76b] Running /usr/bin/env rsync -az --delete tmp/deploy/local/ -e 'ssh -i /Users/kbs/.ssh/id_rsa -p 2202' node@127.0.0.1:/var/www/my_app_path/shared/deploy as kbs@localhost
DEBUG [7c3fd76b] Command: /usr/bin/env rsync -az --delete tmp/deploy/local/ -e 'ssh -i /Users/kbs/.ssh/id_rsa -p 2202' node@127.0.0.1:/var/www/my_app_path/shared/deploy
INFO [7c3fd76b] Finished in 0.319 seconds with exit status 0 (successful).
INFO [0889a0b0] Running /usr/bin/env rsync --archive --acls --xattrs  "/var/www/my_app_path/shared/deploy/" "/var/www/my_app_path/releases/20160209164314/" as node@127.0.0.1
DEBUG [0889a0b0] Command: rsync --archive --acls --xattrs  "/var/www/my_app_path/shared/deploy/" "/var/www/my_app_path/releases/20160209164314/"
INFO [0889a0b0] Finished in 0.049 seconds with exit status 0 (successful).
DEBUG [1a26b1d5] Running /usr/bin/env if test ! -d /var/www/my_app_path/releases/20160209164314; then echo "Directory does not exist '/var/www/my_app_path/releases/20160209164314'" 1>&2; false; fi as node@127.0.0.1
DEBUG [1a26b1d5] Command: if test ! -d /var/www/my_app_path/releases/20160209164314; then echo "Directory does not exist '/var/www/my_app_path/releases/20160209164314'" 1>&2; false; fi
DEBUG [1a26b1d5] Finished in 0.003 seconds with exit status 0 (successful).
INFO [431bcf54] Running /usr/bin/env echo "pablo/" >> REVISION as node@127.0.0.1
DEBUG [431bcf54] Command: cd /var/www/my_app_path/releases/20160209164314 && /usr/bin/env echo "pablo/" >> REVISION
INFO [431bcf54] Finished in 0.004 seconds with exit status 0 (successful).
INFO [ff6800d1] Running /usr/bin/env ln -s /var/www/my_app_path/releases/20160209164314 /var/www/my_app_path/releases/current as node@127.0.0.1
DEBUG [ff6800d1] Command: /usr/bin/env ln -s /var/www/my_app_path/releases/20160209164314 /var/www/my_app_path/releases/current
INFO [ff6800d1] Finished in 0.003 seconds with exit status 0 (successful).
INFO [2bd1eced] Running /usr/bin/env mv /var/www/my_app_path/releases/current /var/www/my_app_path as node@127.0.0.1
DEBUG [2bd1eced] Command: /usr/bin/env mv /var/www/my_app_path/releases/current /var/www/my_app_path
INFO [2bd1eced] Finished in 0.005 seconds with exit status 0 (successful).
DEBUG [815d43cb] Running /usr/bin/env ls -xtr /var/www/my_app_path/releases as node@127.0.0.1
DEBUG [815d43cb] Command: /usr/bin/env ls -xtr /var/www/my_app_path/releases
DEBUG [815d43cb]        20160209145140  20160209145315  20160209145908  20160209160640  20160209161058
20160209164314
DEBUG [815d43cb] Finished in 0.004 seconds with exit status 0 (successful).
INFO Keeping 5 of 6 deployed releases on 127.0.0.1
INFO [dd189670] Running /usr/bin/env rm -rf /var/www/my_app_path/releases/20160209145140 as node@127.0.0.1
DEBUG [dd189670] Command: /usr/bin/env rm -rf /var/www/my_app_path/releases/20160209145140
INFO [dd189670] Finished in 0.004 seconds with exit status 0 (successful).
DEBUG [eda8870d] Running /usr/bin/env if test ! -d /var/www/my_app_path/releases; then echo "Directory does not exist '/var/www/my_app_path/releases'" 1>&2; false; fi as node@127.0.0.1
DEBUG [eda8870d] Command: if test ! -d /var/www/my_app_path/releases; then echo "Directory does not exist '/var/www/my_app_path/releases'" 1>&2; false; fi
DEBUG [eda8870d] Finished in 0.002 seconds with exit status 0 (successful).
INFO [ef9d3787] Running /usr/bin/env echo "Branch master (at pablo/) deployed as release 20160209164314 by kbs" >> /var/www/my_app_path/revisions.log as node@127.0.0.1
DEBUG [ef9d3787] Command: echo "Branch master (at pablo/) deployed as release 20160209164314 by kbs" >> /var/www/my_app_path/revisions.log
INFO [ef9d3787] Finished in 0.002 seconds with exit status 0 (successful).
```

**Comment by komazarari** [comment]
Hm, `deploy_only` task is defined to rsync from local downloaded codes to remote, for example,
* first, deploy myapp normally.
* but for some reason, I must fix the app just a little immediately.
* fix the app located `tmp/deploy/<stage>/` directly, and then `deploy_only` to deploy fixed app.

So this task don't access the bucket. Please excuse me if I misunderstood. May I help you?

**Comment by pablokbs** [comment]
Ok so, good news. I managed to deploy stuff from S3, I didn't know that I needed to put the files on the bucket first. Now capistrano reads the bucket and gets the files, and then deploys them, that's awesome.

I've found a small issue though, even if the file is the same, it makes a new revision, it shouldn't do that. If the files on S3 don't change, capistrano should not create a new revision.

**Comment by komazarari** [comment]
So sorry for my late reply.

like https://github.com/komazarari/capistrano-s3_archive/pull/11#issuecomment-189221084 , I think "should / should not" is not on this plugin discussion.
